#!/bin/bash
#
# Shell Completer - Generate shell completion scripts
# Inspired by zeroclaw completions generation
#

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
BOLD='\033[1m'
RESET='\033[0m'

# Args
TOOL_NAME=""
SHELL_TYPE=""
INSTALL=false
FROM_PACKAGE=false
OUTPUT=""
CUSTOM_OPTS=""

show_help() {
  cat << EOF
Usage: $(basename "$0") <tool-name> [options]

Generate shell completion scripts for CLI tools.

Options:
  --bash              Generate bash completions (default)
  --zsh               Generate zsh completions
  --fish              Generate fish completions
  --install           Auto-install to appropriate directory
  --output <file>    Save to specific file
  --from-package      Generate from package.json scripts
  --opts <list>      Comma-separated list of options
  --help, -h          Show this help

Examples:
  $(basename "$0") my-cli-tool --bash
  $(basename "$0") my-cli-tool --zsh --install
  $(basename "$0") my-cli-tool --opts "--help,--version,--config"
  $(basename "$0") --from-package --bash

EOF
}

# Parse arguments
while [[ $# -gt 0 ]]; do
  case $1 in
    --bash)
      SHELL_TYPE="bash"
      shift
      ;;
    --zsh)
      SHELL_TYPE="zsh"
      shift
      ;;
    --fish)
      SHELL_TYPE="fish"
      shift
      ;;
    --install)
      INSTALL=true
      shift
      ;;
    --output)
      OUTPUT="$2"
      shift 2
      ;;
    --from-package)
      FROM_PACKAGE=true
      shift
      ;;
    --opts)
      CUSTOM_OPTS="$2"
      shift 2
      ;;
    --help|-h)
      show_help
      exit 0
      ;;
    -*)
      echo -e "${RED}Unknown option: $1${RESET}"
      show_help
      exit 1
      ;;
    *)
      if [ -z "$TOOL_NAME" ]; then
        TOOL_NAME="$1"
      fi
      shift
      ;;
  esac
done

# Auto-detect shell if not specified
if [ -z "$SHELL_TYPE" ]; then
  if [ -n "$ZSH_VERSION" ] || [ "${SHELL##*/}" = "zsh" ]; then
    SHELL_TYPE="zsh"
  elif [ -n "$FISH_VERSION" ] || [ "${SHELL##*/}" = "fish" ]; then
    SHELL_TYPE="fish"
  else
    SHELL_TYPE="bash"
  fi
fi

# Generate bash completion
generate_bash() {
  local tool="$1"
  local opts="$2"
  
  cat << EOF
#!/bin/bash
# Completion script for $tool
# Generated by shell-completer

_${tool//-/_}_complete() {
    local cur prev opts
    COMPREPLY=()
    cur="\${COMP_WORDS[COMP_CWORD]}"
    prev="\${COMP_WORDS[COMP_CWORD-1]}"
    opts="$opts"
    
    if [[ \${cur} == -* ]]; then
        COMPREPLY=( \$(compgen -W "\${opts}" -- \${cur}) )
        return 0
    fi
}

complete -F _${tool//-/_}_complete $tool
EOF
}

# Generate zsh completion
generate_zsh() {
  local tool="$1"
  local opts="$2"
  
  cat << EOF
#compdef $tool
# Completion script for $tool
# Generated by shell-completer

_${tool//-/_}() {
    local opts=($opts)
    _arguments -C \\
        "*: :->args" \\
        "*::arg:->args"
    
    case "\$state" in
        args)
            _describe -t options 'options' opts
            ;;
    esac
}

compdef _${tool//-/_} $tool
EOF
}

# Generate fish completion
generate_fish() {
  local tool="$1"
  local opts="$2"
  
  cat << EOF
# Completion script for $tool
# Generated by shell-completer

EOF
  
  # Parse options and generate fish completions
  echo "$opts" | tr ' ' '\n' | while read -r opt; do
    if [ -n "$opt" ]; then
      echo "complete -c $tool -l ${opt#--}"
    fi
  done
}

# Extract options from package.json
get_options_from_package() {
  local opts=""
  
  if [ -f "package.json" ]; then
    # Try to extract common CLI options from scripts
    if command -v jq >/dev/null 2>&1; then
      local scripts=$(jq -r '.scripts | keys[]' package.json 2>/dev/null | head -10)
      if [ -n "$scripts" ]; then
        opts="--help --version"
        # Add script names as potential subcommands
        for script in $scripts; do
          opts="$opts $script"
        done
      fi
    fi
  fi
  
  # Default fallback
  if [ -z "$opts" ]; then
    opts="--help --version --config --verbose --quiet --debug"
  fi
  
  echo "$opts"
}

# Get options
if [ -n "$CUSTOM_OPTS" ]; then
  OPTIONS=$(echo "$CUSTOM_OPTS" | tr ',' ' ')
elif [ "$FROM_PACKAGE" = true ]; then
  OPTIONS=$(get_options_from_package)
else
  # Default options for unknown tool
  OPTIONS="--help --version --verbose --quiet --config --debug"
fi

# Generate completion
if [ -z "$TOOL_NAME" ] && [ "$FROM_PACKAGE" != true ]; then
  echo -e "${RED}Error: Tool name required${RESET}"
  show_help
  exit 1
fi

# Use package name if --from-package
if [ "$FROM_PACKAGE" = true ] && [ -z "$TOOL_NAME" ]; then
  if command -v jq >/dev/null 2>&1 && [ -f "package.json" ]; then
    TOOL_NAME=$(jq -r '.name' package.json 2>/dev/null | xargs basename)
  fi
  if [ -z "$TOOL_NAME" ] || [ "$TOOL_NAME" = "null" ]; then
    echo -e "${RED}Error: Could not determine tool name from package.json${RESET}"
    exit 1
  fi
fi

case "$SHELL_TYPE" in
  bash)
    COMPLETION=$(generate_bash "$TOOL_NAME" "$OPTIONS")
    ;;  
  zsh)
    COMPLETION=$(generate_zsh "$TOOL_NAME" "$OPTIONS")
    ;;
  fish)
    COMPLETION=$(generate_fish "$TOOL_NAME" "$OPTIONS")
    ;;
  *)
    echo -e "${RED}Unknown shell type: $SHELL_TYPE${RESET}"
    exit 1
    ;;
esac

# Output
if [ -n "$OUTPUT" ]; then
  echo "$COMPLETION" > "$OUTPUT"
  chmod +x "$OUTPUT"
  echo -e "${GREEN}✓ Completion script saved to: $OUTPUT${RESET}"
elif [ "$INSTALL" = true ]; then
  # Determine install location
  INSTALL_DIR=""
  case "$SHELL_TYPE" in
    bash)
      INSTALL_DIR="${BASH_COMPLETION_USER_DIR:-$HOME/.bash_completion.d}"
      ;;
    zsh)
      INSTALL_DIR="${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/completions"
      if [ ! -d "$INSTALL_DIR" ]; then
        INSTALL_DIR="$HOME/.zsh/completions"
      fi
      ;;
    fish)
      INSTALL_DIR="$HOME/.config/fish/completions"
      ;;
  esac
  
  if [ -n "$INSTALL_DIR" ]; then
    mkdir -p "$INSTALL_DIR"
    local file="$INSTALL_DIR/_$TOOL_NAME"
    echo "$COMPLETION" > "$file"
    chmod +x "$file"
    echo -e "${GREEN}✓ Completion installed to: $file${RESET}"
    echo -e "${YELLOW}Note: You may need to restart your shell or source your config file${RESET}"
  else
    echo -e "${YELLOW}! Could not determine install location${RESET}"
    echo "$COMPLETION"
  fi
else
  echo "$COMPLETION"
fi
