/**
 * Report Generation
 * Format diagnostic results for export
 */

/**
 * Generate a formatted report
 * @param {Object} results - Diagnostic results
 * @param {string} format - Output format (markdown, json)
 * @returns {string} Formatted report
 */
function generate(results, format) {
  switch (format) {
    case 'json':
      return generateJSON(results);
    case 'markdown':
    default:
      return generateMarkdown(results);
  }
}

function generateMarkdown(results) {
  const lines = [];
  
  // Header
  lines.push('# PopeBot Doctor Diagnostic Report\n');
  lines.push(`**Generated:** ${results.meta?.timestamp || new Date().toISOString()}\n`);
  lines.push(`**Version:** ${results.meta?.version || '1.0.0'}\n`);
  lines.push(`**Duration:** ${results.meta?.duration || 'unknown'}\n`);
  lines.push('---\n');
  
  // Summary
  lines.push('## Summary\n');
  lines.push(`| Metric | Count |`);
  lines.push(`|--------|-------|`);
  lines.push(`| ✅ OK | ${results.summary?.ok || 0} |`);
  lines.push(`| ⚠️  Warning | ${results.summary?.warning || 0} |`);
  lines.push(`| ❌ Error | ${results.summary?.error || 0} |`);
  lines.push(`| **Total** | **${results.summary?.total || 0}** |\n`);
  
  // Overall status
  const hasErrors = (results.summary?.error || 0) > 0;
  const hasWarnings = (results.summary?.warning || 0) > 0;
  
  if (hasErrors) {
    lines.push('**Status:** ❌ Issues found requiring attention\n');
  } else if (hasWarnings) {
    lines.push('**Status:** ⚠️ Healthy with warnings\n');
  } else {
    lines.push('**Status:** ✅ All systems healthy\n');
  }
  
  lines.push('---\n');
  
  // Group by category
  const byCategory = groupByCategory(results.items || []);
  
  for (const [category, items] of Object.entries(byCategory)) {
    lines.push(`\n## ${category.charAt(0).toUpperCase() + category.slice(1)}\n`);
    
    // Sort: errors first, then warnings, then ok
    const sorted = items.sort((a, b) => {
      const severityOrder = { error: 0, warning: 1, ok: 2 };
      return (severityOrder[a.severity] || 3) - (severityOrder[b.severity] || 3);
    });
    
    for (const item of sorted) {
      const icon = item.severity === 'ok' ? '✅' : (item.severity === 'warning' ? '⚠️' : '❌');
      lines.push(`### ${icon} ${item.check}\n`);
      lines.push(`**Message:** ${item.message}\n`);
      if (item.details) {
        lines.push(`**Details:** ${item.details}\n`);
      }
      if (item.remediation) {
        lines.push(`**Fix:** ${item.remediation}\n`);
      }
      lines.push('');
    }
  }
  
  // Footer
  lines.push('---\n');
  lines.push('*Report generated by PopeBot Doctor*\n');
  
  return lines.join('\n');
}

function generateJSON(results) {
  return JSON.stringify(results, null, 2);
}

function groupByCategory(items) {
  const grouped = {};
  for (const item of items) {
    if (!grouped[item.category]) {
      grouped[item.category] = [];
    }
    grouped[item.category].push(item);
  }
  return grouped;
}

module.exports = { generate };
