#!/usr/bin/env node
/**
 * SkillForge Manifest Generator - Generate PopeBot skill manifests
 * 
 * Creates SKILL.md files for integrating discovered skills into PopeBot.
 */

const fs = require('fs');
const path = require('path');

// Configuration
const CONFIG = {
  outputDir: process.env.SKILLFORGE_OUTPUT_DIR || '/job/tmp/skills'
};

// Parse command line arguments
const args = process.argv.slice(2);
const options = {
  name: null,
  url: null,
  description: null,
  language: 'JavaScript',
  version: '0.1.0'
};

for (let i = 0; i < args.length; i++) {
  if ((args[i] === '--name' || args[i] === '-n') && args[i + 1]) {
    options.name = args[i + 1];
    i++;
  } else if ((args[i] === '--url' || args[i] === '-u') && args[i + 1]) {
    options.url = args[i + 1];
    i++;
  } else if ((args[i] === '--description' || args[i] === '-d') && args[i + 1]) {
    options.description = args[i + 1];
    i++;
  } else if ((args[i] === '--language' || args[i] === '-l') && args[i + 1]) {
    options.language = args[i + 1];
    i++;
  } else if ((args[i] === '--version' || args[i] === '-v') && args[i + 1]) {
    options.version = args[i + 1];
    i++;
  } else if (args[i] === '--help' || args[i] === '-h') {
    console.log(`
SkillForge Manifest Generator - Generate PopeBot skill manifests

Usage: node generate.js --name <name> --url <url> --description <desc> [options]

Required Options:
  --name, -n <name>          Skill name (will be used as directory name)
  --url, -u <url>            Source repository URL
  --description, -d <desc>   Skill description

Optional Options:
  --language, -l <lang>      Programming language (default: JavaScript)
  --version, -v <version>    Version number (default: 0.1.0)
  --help, -h                 Show this help message

Environment Variables:
  SKILLFORGE_OUTPUT_DIR      Output directory (default: /job/tmp/skills)

Examples:
  node generate.js --name "example-skill" \\
    --url "https://github.com/user/example-skill" \\
    --description "An example skill for PopeBot"

  node generate.js -n "my-skill" -u "https://github.com/user/repo" -d "Does something"
`);
    process.exit(0);
  }
}

// Validate required options
if (!options.name) {
  console.error('Error: --name is required');
  process.exit(1);
}
if (!options.url) {
  console.error('Error: --url is required');
  process.exit(1);
}
if (!options.description) {
  console.error('Error: --description is required');
  process.exit(1);
}

// Sanitize skill name for use as directory
function sanitizeName(name) {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9-_]/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '');
}

// Extract owner from URL
function extractOwner(url) {
  const match = url.match(/github\.com\/([^\/]+)/);
  return match ? match[1] : 'unknown';
}

// Generate SKILL.md content
function generateSkillMd(options) {
  const safeName = sanitizeName(options.name);
  const owner = extractOwner(options.url);
  const now = new Date().toISOString().split('T')[0];

  return `---
name: ${safeName}
description: ${options.description}
---

# ${options.name}

> Auto-generated by SkillForge on ${now}

## Overview

- **Source**: [${options.url}](${options.url})
- **Owner**: ${owner}
- **Language**: ${options.language}
- **Version**: ${options.version}

## Description

${options.description}

## Installation

\`\`\`bash
# Clone or download the skill repository
cd /job/pi-skills/${safeName}

# Install dependencies (if any)
npm install
\`\`\`

## Usage

\`\`\`bash
# Basic usage example
{baseDir}/script.js [arguments]

# With options
{baseDir}/script.js --option value
\`\`\`

## Configuration

Add required environment variables to your \`.env\` file:

\`\`\`bash
# Example configuration
EXAMPLE_API_KEY="your-api-key-here"
\`\`\`

## When to Use

- Use case 1
- Use case 2
- Use case 3

## Notes

> ⚠️ **Review Required**: This skill manifest was auto-generated from repository metadata.
> Review the source repository and adapt the usage examples before enabling in production.

## Links

- [Source Repository](${options.url})
- [Issues](${options.url}/issues)
- [Releases](${options.url}/releases)

---

*Generated by PopeBot SkillForge - Based on ZeroClaw's SkillForge architecture*
`;
}

// Generate package.json template
function generatePackageJson(options) {
  const safeName = sanitizeName(options.name);
  
  return JSON.stringify({
    name: `popebot-skill-${safeName}`,
    version: options.version,
    description: options.description,
    main: 'index.js',
    scripts: {
      test: 'echo "Error: no test specified" && exit 1'
    },
    keywords: [
      'popebot',
      'skill',
      'ai-agent',
      'automation'
    ],
    author: extractOwner(options.url),
    license: 'MIT',
    dependencies: {}
  }, null, 2);
}

// Generate README.md template
function generateReadme(options) {
  const safeName = sanitizeName(options.name);
  const now = new Date().toISOString().split('T')[0];

  return `# ${options.name}

${options.description}

> ⚠️ **Auto-generated skill** - This skill was created by SkillForge and requires manual review before use.

## Installation

\`\`\`bash
# From the PopeBot root directory
cd pi-skills/${safeName}
npm install
\`\`\`

## Activation

\`\`\`bash
# Create symlink to activate the skill
ln -s ../../pi-skills/${safeName} .pi/skills/${safeName}
\`\`\`

## Usage

TBD - Add usage instructions after reviewing the source repository

## Configuration

TBD - Add configuration requirements after reviewing the source repository

## Development

This skill was auto-generated from: ${options.url}

Review the source repository for:
- Actual implementation details
- API requirements
- Configuration options
- Usage examples

## License

See source repository for license information.

---

*Generated by PopeBot SkillForge on ${now}*
`;
}

// Generate integration script
function generateIntegrationScript(options) {
  const safeName = sanitizeName(options.name);
  
  return `#!/bin/bash
# Integration script for ${options.name}
# Auto-generated by SkillForge

set -e

SKILL_NAME="${safeName}"
SKILL_DIR="/job/pi-skills/${safeName}"
SYMLINK_DIR="/job/.pi/skills/${safeName}"

echo "=== Integrating ${options.name} ==="
echo ""

# Check if skill directory exists
if [ ! -d "$SKILL_DIR" ]; then
    echo "Creating skill directory..."
    mkdir -p "$SKILL_DIR"
fi

# Check if already activated
if [ -L "$SYMLINK_DIR" ] || [ -d "$SYMLINK_DIR" ]; then
    echo "Warning: Skill already exists at $SYMLINK_DIR"
    echo "Remove it first with: rm $SYMLINK_DIR"
    exit 1
fi

# Create symlink to activate
echo "Creating symlink to activate skill..."
ln -s "../../pi-skills/${safeName}" "$SYMLINK_DIR"

echo ""
echo "✅ Skill activated successfully!"
echo ""
echo "Next steps:"
echo "1. Review the skill at: $SKILL_DIR"
echo "2. Install dependencies: cd $SKILL_DIR && npm install"
echo "3. Test the skill: {baseDir}/script.js"
echo ""
`;
}

// Main generation function
function generate() {
  const safeName = sanitizeName(options.name);
  const skillDir = path.join(CONFIG.outputDir, safeName);
  
  console.log('=== SkillForge Manifest Generator ===\n');
  console.log(`Generating skill: ${options.name}`);
  console.log(`Source: ${options.url}`);
  console.log(`Output directory: ${skillDir}\n`);

  // Create directory
  fs.mkdirSync(skillDir, { recursive: true });

  // Generate SKILL.md
  const skillMdPath = path.join(skillDir, 'SKILL.md');
  const skillMdContent = generateSkillMd(options);
  fs.writeFileSync(skillMdPath, skillMdContent);
  console.log(`✓ Created SKILL.md`);

  // Generate package.json
  const packageJsonPath = path.join(skillDir, 'package.json');
  const packageJsonContent = generatePackageJson(options);
  fs.writeFileSync(packageJsonPath, packageJsonContent);
  console.log(`✓ Created package.json`);

  // Generate README.md
  const readmePath = path.join(skillDir, 'README.md');
  const readmeContent = generateReadme(options);
  fs.writeFileSync(readmePath, readmeContent);
  console.log(`✓ Created README.md`);

  // Generate integration script
  const integratePath = path.join(skillDir, 'integrate.sh');
  const integrateContent = generateIntegrationScript(options);
  fs.writeFileSync(integratePath, integrateContent, { mode: 0o755 });
  console.log(`✓ Created integrate.sh`);

  // Generate metadata JSON
  const metadataPath = path.join(skillDir, 'metadata.json');
  const metadata = {
    name: safeName,
    displayName: options.name,
    description: options.description,
    source: options.url,
    language: options.language,
    version: options.version,
    generatedAt: new Date().toISOString(),
    generator: 'SkillForge',
    status: 'pending-review',
    requiresReview: true
  };
  fs.writeFileSync(metadataPath, JSON.stringify(metadata, null, 2));
  console.log(`✓ Created metadata.json`);

  console.log('\n=== Generation Complete ===\n');
  console.log(`Skill manifest generated at: ${skillDir}`);
  console.log('\nTo integrate this skill:');
  console.log(`1. Review the generated files in: ${skillDir}`);
  console.log(`2. Move to pi-skills directory:`);
  console.log(`   mv ${skillDir} /job/pi-skills/${safeName}`);
  console.log(`3. Run the integration script:`);
  console.log(`   /job/pi-skills/${safeName}/integrate.sh`);
  console.log(`\nOr manually:`);
  console.log(`   cd /job/pi-skills/${safeName}`);
  console.log(`   npm install`);
  console.log(`   ln -s ../../pi-skills/${safeName} /job/.pi/skills/${safeName}`);
  console.log('');

  return skillDir;
}

try {
  generate();
} catch (error) {
  console.error('Generation failed:', error.message);
  process.exit(1);
}
